[green_agent]
agentbeats_id = "019bc37e-fde8-79f1-92dc-610a92df8faf"
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "role_1_name"
env = {}

[[participants]]
agentbeats_id = ""
name = "role_2_name"
env = {}

[config]
# Add your assessment config here
